version: "3.7"

networks:
  authz-custom-network:
  
services:
  authz-custom-sqlserver:
    image: "mcr.microsoft.com/azure-sql-edge"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "2@LaiNw)PDvs^t>L!Ybt]6H^%h3U>M"
        ACCEPT_EULA: "Y"
    networks:
      - authz-custom-network
  authz-idsrv:
    build:
      context: ./src/IdentityServer
      dockerfile: Dockerfile
    ports:
     - "5002:80"
    networks:
      - authz-custom-network
